---
kind: Pod
apiVersion: v1
metadata:
  name: coredns
  namespace: openshift-kni-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kni-infra-mdns
spec:
  volumes:
  - name: resource-dir
    hostPath:
      path: "/etc/kubernetes/static-pod-resources/coredns"
  - name: kubeconfig
    hostPath:
      path: "/etc/kubernetes/kubeconfig"
  - name: conf-dir
    empty-dir: {}
  - name: manifests
    hostPath:
      path: "/opt/openshift/manifests"
  initContainers:
  - name: render-corefile
    image: quay.io/openshift/origin-node:latest
    command:
    - "/bin/bash"
    - "-c"
    - |
      #/bin/bash
      set -ex
      API_DNS="$(awk -F[/:] '/apiServerURL/ {print $5}' /opt/openshift/manifests/cluster-infrastructure-02-config.yml)"
      DOMAIN="${API_DNS#*.}"
      read -r -d '.' -a CLUSTER_ARR <<< "$DOMAIN"
      NAME=${CLUSTER_ARR[0]}
      API_VIP="$(dig +noall +answer "$API_DNS" | awk '{print $NF}')"
      DNS_VIP="$(dig +noall +answer "ns1.${DOMAIN}" | awk '{print $NF}')"
      grep -Ev "${DNS_VIP}|127.0.0.1" /etc/resolv.conf | tee /etc/coredns/resolv.conf
      NUM_DNS_MEMBERS=$(grep -A 5 'controlPlane' /opt/openshift/manifests/cluster-config.yaml | awk '/replicas/ {print $2}')
      export API_VIP DOMAIN NAME NUM_DNS_MEMBERS
      /usr/libexec/platform-python -c "from __future__ import print_function
      import os
      with open('/etc/kubernetes/static-pod-resources/Corefile.tmpl', 'r') as f:
          content = f.read()
      with open('/etc/coredns/Corefile', 'w') as dest:
          print(os.path.expandvars(content), file=dest)"
    resources: {}
    volumeMounts:
    - name: resource-dir
      mountPath: "/etc/kubernetes/static-pod-resources"
    - name: conf-dir
      mountPath: "/etc/coredns"
    - name: manifests
      mountPath: "/opt/openshift/manifests"
  containers:
  - name: coredns
    securityContext:
      privileged: true
    image: quay.io/openshift-metal3/coredns-mdns:latest
    args:
    - "--conf"
    - "/etc/coredns/Corefile"
    resources:
      requests:
        cpu: 150m
        memory: 1Gi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/coredns"
    terminationMessagePolicy: FallbackToLogsOnError
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
